// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://innytbjrkaeowoypgeog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlubnl0Ympya2Flb3dveXBnZW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MTk0MDIsImV4cCI6MjA3Njk5NTQwMn0.BZQ6N3p1WNl_fo1wqNvFr-wYvoCcAk0UFAagZJORx28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});